[bugfix] fix runtime crash on release apk crash: java.lang.NoSuchMethodError solution: add MINIFY_MEMBER_REMOVED type to create _jugg_fix class instead of recompile which may not have source file if it's in .aar