[bugfix] fix NoSuchMethodError when add an optional argument to a top level function, and compile declaration file and invoke file together reason: kotlin compiler will priority use .kotlin_module in "-cp" instead of the source code